services:
  - type: web
    name: duracloud-retrieval
    env: docker
    dockerfilePath: app/docker/Dockerfile
    envVars:
      - key: HOST
        sync: false
      - key: PORT
        value: 8080
    disk:
      name: data
      mountPath: /app/downloads
      sizeGB: 1