version: '3.8'

services:
  duracloud-retrieval:
    build:
      context: ../..
      dockerfile: app/docker/Dockerfile
    ports:
      - "${FLASK_PORT:-8080}:8080"
    env_file:
      - ../../app/.env
    volumes:
      - ../../duracloud-logs:/root/duracloud-retrieval-work
      - ../../downloads:/app/downloads
      - ../../app/frontend:/app/frontend

volumes:
  duracloud-logs: 